# Form implementation generated from reading ui file 'ui\main\home.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import (QWidget, QLabel,
                             QVBoxLayout,
                             QSizePolicy, QSpacerItem)

from modules.main_ui import widgets

class Ui_Form(QWidget):
    def __init__(self) -> None:
        super().__init__()
    
        layout = QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        data = widgets.Ui_Form('Загружено', [1, 2, 3], '', lambda a: a, '', lambda b: b)
        layout.addWidget(data)
        data = widgets.Ui_Form('Выгружено', [1, 2, 3, 4, 5, 6, 7, 8], '', lambda a: a, '', lambda b: b)
        layout.addWidget(data)

        spacer = QSpacerItem(1, 1, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        layout.addItem(spacer)

        self.setLayout(layout)