# Form implementation generated from reading ui file 'ui\main\home.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import QWidget, QLabel, QGridLayout


class Ui_Form(QWidget):
    def __init__(self) -> None:
        super().__init__()
    
        grid_layout = QGridLayout()
        label = QLabel('Редактор')
        grid_layout.addWidget(label)
        self.setLayout(grid_layout)